services:
  noise-guard-bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: MesGuard_Bot
    env_file:
      - .env
    environment:
      - DB_PATH=/data/noise_guard.db
    volumes:
      - ./data:/data
    restart: unless-stopped

  noise-guard-watcher:
    build:
      context: .
      dockerfile: watcher/Dockerfile
    container_name: MesGuard_Watcher
    env_file:
      - .env
    environment:
      - DB_PATH=/data/noise_guard.db
    volumes:
      - ./data:/data
    restart: unless-stopped
